appr:
- &id001
  name: pfs-ui
  repository: file://appr_charts/willismorsecoreinfo/pfs-ui
  version: 0.1.0
dependencies:
- name: products
  repository: https://raw.githubusercontent.com/willismorse/microservices-demo-microfrontend-products/master/
  version: 0.1.2
- *id001
- name: hostapp
  repository: https://raw.githubusercontent.com/willismorse/microservices-demo-microfrontend-hostapp/master/
  version: 0.1.1
