dependencies:
   - name: hostapp
     version: 0.1.1
     repository: https://raw.githubusercontent.com/willismorse/microservices-demo-microfrontend-hostapp/master/
   - name: products
     version: 0.1.2
     repository: https://raw.githubusercontent.com/willismorse/microservices-demo-microfrontend-products/master/    