apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - host:
    http:
      paths:
      - path: /products
        backend:
          serviceName: products
          servicePort: 8080
      - path: /
        backend:
          serviceName: hostapp
          servicePort: 8080
      - path: /pfs-ui
        backend:
          serviceName: pfs-ui
          servicePort: 8080

