apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  rules:
  - host:
    http:
      paths:
      - path: /products
        backend:
          serviceName: products
          servicePort: 8080
      - path: /header
        backend:
          serviceName: header
          servicePort: 8080    
      - path: /
        backend:
          serviceName: hostapp
          servicePort: 8080
      - path: /catalogue
        backend:
          serviceName: catalogue
          servicePort: 80
      

